project:
  name: prog-data-sync-tool
  description: ''
  tools: []
  current_focus: ''
  needs: []
  links:
    docs: ''
    staging: ''
    production: ''
  team:
    lead: willlevinson
    contributors:
    - jjackson12
    - pauldingus
    - dladanyi
    - nestrada79
    - emilyriederer
  campaign:
    candidate: ''
    office: ''
  auto_refresh: true
